definitions:
  errs.Error:
    properties:
      message:
        type: string
    type: object
  errs.ValidationError:
    properties:
      errors:
        additionalProperties:
          type: string
        type: object
      message:
        type: string
    type: object
  handler.Response-array_models_FriendOutPutModel:
    properties:
      data:
        items:
          $ref: '#/definitions/models.FriendOutPutModel'
        type: array
      message:
        type: string
      status:
        type: integer
    type: object
  handler.Response-bool:
    properties:
      data:
        type: boolean
      message:
        type: string
      status:
        type: integer
    type: object
  handler.Response-models_UserProfileOutPutModel:
    properties:
      data:
        $ref: '#/definitions/models.UserProfileOutPutModel'
      message:
        type: string
      status:
        type: integer
    type: object
  handler.Response-uuid_UUID:
    properties:
      data:
        type: string
      message:
        type: string
      status:
        type: integer
    type: object
  models.FriendOutPutModel:
    properties:
      firstName:
        type: string
      id:
        type: string
      lastName:
        type: string
      profile:
        type: string
      username:
        type: string
    type: object
  models.UserChangePasswordInputModel:
    properties:
      newPassword:
        type: string
      password:
        type: string
    type: object
  models.UserChangeProfileInputModel:
    properties:
      bio:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      mobile:
        type: string
      username:
        type: string
    type: object
  models.UserProfileOutPutModel:
    properties:
      bio:
        type: string
      firstName:
        type: string
      id:
        type: string
      lastName:
        type: string
      mobile:
        type: string
      profile:
        type: string
      roleId:
        type: string
      roleName:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /friend:
    get:
      consumes:
      - application/json
      parameters:
      - description: search term
        in: query
        name: searchTern
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Response-array_models_FriendOutPutModel'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errs.Error'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/errs.ValidationError'
      security:
      - Bearer: []
      tags:
      - friend
  /friend/make/{friendId}:
    post:
      consumes:
      - application/json
      parameters:
      - description: friend id
        in: path
        name: friendId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Response-uuid_UUID'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errs.Error'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/errs.ValidationError'
      security:
      - Bearer: []
      tags:
      - friend
  /friend/remove/{friendId}:
    post:
      consumes:
      - application/json
      parameters:
      - description: friend id
        in: path
        name: friendId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Response-bool'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errs.Error'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/errs.ValidationError'
      security:
      - Bearer: []
      tags:
      - friend
  /profile:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Response-models_UserProfileOutPutModel'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errs.Error'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/errs.ValidationError'
      security:
      - Bearer: []
      tags:
      - profile
    post:
      consumes:
      - application/json
      parameters:
      - description: input model
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.UserChangeProfileInputModel'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Response-models_UserProfileOutPutModel'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errs.Error'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/errs.ValidationError'
      security:
      - Bearer: []
      tags:
      - profile
  /profile/change-password:
    post:
      consumes:
      - application/json
      parameters:
      - description: input model
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.UserChangePasswordInputModel'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Response-uuid_UUID'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errs.Error'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/errs.ValidationError'
      security:
      - Bearer: []
      tags:
      - profile
swagger: "2.0"
