app:
  address: 127.0.0.1
  port: 3005
  url: http://127.0.0.1:3005
  
consul:
  enable: true
  ttl: 10
  check_duration: 7
  check_id: chat-service-check-alive
  id: chat-service
  cluster_name: chess-microservices
  tags: 
    - chat-application

database:
  host: localhost
  port: 5464
  name: chess
  username: chess
  password: 12345678
  sslmode: disable

redis:
  host: 127.0.0.1
  port: 6380
  db: 0
  password: 12345678

rabbitmq:
  username: guest
  password: guest
  address: 127.0.0.1:5672