app:
  address: 127.0.0.1
  port: 3004
  url: http://127.0.0.1:3004
  files_download_prefix: http://localhost:3000/media/uploads

consul:
  enable: true
  ttl: 10
  check_duration: 7
  check_id: user-service-check-alive
  id: user-service
  cluster_name: chess-microservices
  tags: 
    - user-application

database:
  host: localhost
  port: 5464
  name: chess
  username: chess
  password: 12345678
  sslmode: disable

rabbitmq:
  username: guest
  password: guest
  address: 127.0.0.1:5672