app:
  address: 127.0.0.1
  port: 3002

consul:
  enable: true
  ttl: 10
  check_duration: 7
  check_id: game-service-check-alive
  id: game-service
  cluster_name: chess-microservices
  tags: 
    - game-application

database:
  host: localhost
  port: 5464
  name: chess
  username: chess
  password: 12345678
  sslmode: disable